print("Hello World")
num1= input("enter a number: ")
num2= input("enter another number: ")
num3= int(num1) + int(num2)
num4= int(num1) - int(num2)
num5= int(num1) * int(num2)
num6= int(num1) / int(num2)
print("Addition: ",num3)
print("Substraction: ", num4)
print("Multiplication: ", num5)
print("Division: ",num6)
